// Code generated by mockery v2.35.3. DO NOT EDIT.

package notificationsdk

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v2 "gitlab.com/bavatech/architecture/software/libs/go-modules/notificationsdk.git/v2"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: ctx, payload
func (_m *Client) SendEmail(ctx context.Context, payload v2.EmailRequest) error {
	ret := _m.Called(ctx, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, v2.EmailRequest) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendWebhook provides a mock function with given fields: ctx, payload
func (_m *Client) SendWebhook(ctx context.Context, payload v2.WebhookNotifyRequest) error {
	ret := _m.Called(ctx, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, v2.WebhookNotifyRequest) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendWhatsapp provides a mock function with given fields: ctx, payload
func (_m *Client) SendWhatsapp(ctx context.Context, payload v2.WhatsappNotifyRequest) error {
	ret := _m.Called(ctx, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, v2.WhatsappNotifyRequest) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
